CREATE TABLE `alert_rules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`enabled` boolean NOT NULL DEFAULT true,
	`severityThreshold` enum('critical','high','medium','low') NOT NULL DEFAULT 'high',
	`cvssThreshold` float,
	`watchedServices` json,
	`watchedTargets` json,
	`watchedCveIds` json,
	`alertOnKev` boolean NOT NULL DEFAULT true,
	`channels` json,
	`cooldownMinutes` int DEFAULT 60,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `alert_rules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ruleId` int,
	`scanId` int,
	`hostId` int,
	`portId` int,
	`severity` enum('critical','high','medium','low','info') NOT NULL DEFAULT 'high',
	`title` varchar(512) NOT NULL,
	`message` text,
	`cveId` varchar(64),
	`cvssScore` float,
	`service` varchar(128),
	`serviceVersion` varchar(128),
	`targetIp` varchar(45),
	`portNumber` int,
	`status` enum('new','acknowledged','investigating','resolved','dismissed') NOT NULL DEFAULT 'new',
	`notificationSent` boolean NOT NULL DEFAULT false,
	`notifiedAt` timestamp,
	`resolvedBy` int,
	`resolutionNotes` text,
	`resolvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `alerts_id` PRIMARY KEY(`id`)
);
